#!/bin/sh
echo c2VydmVyIHsKICAgICAgICBsaXN0ZW4gODAgZGVmYXVsdF9zZXJ2ZXI7CiAgICAgICAgbGlzdGVuIFs6Ol06ODAgZGVmYXVsdF9zZXJ2ZXI7CiAgICAgICAgaW5kZXggaW5kZXguaHRtbCBpbmRleC5odG0gaW5kZXgubmdpbngtZGViaWFuLmh0bWw7CiAgICAgICAgc2VydmVyX25hbWUgXzsKICAgICAgICBsb2NhdGlvbiAvIHsKICAgICAgICAgICAgICAgIHByb3h5X3Bhc3MgaHR0cDovLzEyNy4wLjAuMTo4MDgwOwogICAgICAgICAgICAgICAgaW5kZXggIGluZGV4Lmh0bWwgaW5kZXguaHRtIGluZGV4LmpzcDsKICAgICAgICB9CiAgICAgICAgbG9jYXRpb24gfiBeL3VwbG9hZC8uKlwuanNwJCB7CiAgICAgICAgICAgICAgICBwcm94eV9wYXNzIGh0dHA6Ly8xMjcuMC4wLjE6ODA4MDsKICAgICAgICAgICAgICAgIGRlbnkgYWxsOwogICAgICAgIH0KfQ==|base64 -d > /etc/nginx/sites-available/default
/etc/init.d/nginx restart
chmod 4755 /readflag
echo $FLAG > /root/flag
chmod 700 /flag
export FLAG=flag_not_here
FLAG=flag_not_here
